### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by junorouse** [junorouse/secuinside2017-pwn1#1]
- [x] emulate 부분 obfuscation.
- [x] mapping 부분 암호화.
- [x] vm 제작 (CODE_RIP 잘 하기) underflow 막기 <- underflow 하면 유저 input값 들어감.
- [x] 테스트 케이스 만드는거 만들기
- [x] 답안 체크하는 부분 만들기

**Comment by junorouse** [comment]
어차피 CODE_RIP 는 unsigned라 underflow날일이 없음.

**Comment by junorouse** [comment]
mapping 하는 부분만 짜면됨
